### ISSUE TITLE
Any ways to fix it?

### ISSUE THREAD

**Issue by dewxo** [mapluisch/ChatGPT-without-login#2]
![image](https://github.com/mapluisch/ChatGPT-without-login/assets/157586672/c2aa317f-ecc7-400d-816b-6c4d9df8975b)

Command:
python gpt.py -p "Tell me the architecture of chatgpt"

**Comment by mapluisch** [comment]
Hey dewxo,

Sorry for the super late reply, I've been pretty busy and just got around to fixing the scripts.
Both scripts now make use of Playwright as browser lib and use Firefox as backend which fixes the bug you've encountered. Please pull the latest scripts and try again 😊

Hope this helps!
