### ISSUE TITLE
any plan to extend for a login account

### ISSUE THREAD

**Issue by thangckt** [mapluisch/ChatGPT-without-login#3]
hi @mapluisch 

Do you have any plan to extend this work that allow to login via cookies (for example)?

Thank.

**Comment by mapluisch** [comment]
Hey @thangckt,

That's a nice idea I haven't thought about yet - I will look into it. Thanks for your suggestion!

**Comment by thangckt** [comment]
@mapluisch 
hope to see that :), [someone](https://github.com/nek0us/ChatGPT) already do it, but the code is looked cumbersome and may not efficient. You may have idea to make it simpler.

I am facing the problem that `playwright` may not work with Jupyter in Windows, as discussed [here](https://stackoverflow.com/questions/75203392/trying-to-use-playwright-in-jupyterlabs-not-implemented)
Someone propose solution, but it looks complicated.
Do you have any simple idea for that?

Thank.

**Comment by mapluisch** [comment]
Sorry, I'm using macOS myself so I can't really tell you anything about that. I could boot up my Windows VM and see if I can replicate the playwright-related error.

Just added a new `-st` token flag based on your suggestion, feel free to check it out 😊
Will close this issue for now and potentially re-open if I get around to checking out the Jupyter stuff on my VM.
