### ISSUE TITLE
not bypass Cloudflare

### ISSUE THREAD

**Issue by thangckt** [mapluisch/ChatGPT-without-login#4]
hi @mapluisch 

I get this error
```
Cannot find the prompt input on the webpage.
Please check whether you have access to chatgpt.com without logging in via your browser.
```
I can access chatgpt.com without logging in via your browser.

When show browser from your code, I see a Cloudfare check, and it may be a problem.

**Comment by thangckt** [comment]
solve by move the page.reload into if command (line 45, python file)

**Comment by RasaJun** [comment]
How you solve? can you show me your code? thx!
